### ISSUE TITLE
Example for the setup

### ISSUE THREAD

**Issue by anoopsinghbayes** [omarkhatibco/tailwind-css-variables#1]
can you provide a good working example to set this up

**Comment by omarkhatibgg** [comment]
Hi @anoopsinghbayes  
There is an Example in Readme.
but it's not organised, I will fix it and back to you.

**Comment by omarkhatibgg** [comment]
Hi @anoopsinghbayes 

check the readme again here.

[https://github.com/omarkhatibco/tailwind-css-variables#configure](readme)

You just need to add this to your plugin section in `tailwind.js` or `tailwind.config.js`

```js
plugins: {
  require('tailwind-css-variables')();
}
```

Feel free to open this issue again if you still have questions.

**Comment by omarkhatibgg** [comment]
Hi @anoopsinghbayes 

I made an example with tailwind playground, you can check it.

https://github.com/omarkhatibco/playground

**Comment by idmytro** [comment]
I don't see any css variables here https://github.com/omarkhatibco/playground

Please provide an example

**Comment by ilovelaravel** [comment]
@omarkhatibco 
it dumped all vars and ignored purgecss.. is that correct? Filesize multiplier?

**Comment by omarkhatibgg** [comment]
Hi @ilovelaravel 
it's correct, purgecss has the ability to remove  unused css rules only not css variables.

because some time you need this variables in the browser to be able to change theme or use theme in JS.
