### ISSUE TITLE
Using a tuple of the form [fontSize, { letterSpacing, lineHeight }]  result in [object Object] in CSS variables.

### ISSUE THREAD

**Issue by kiril-daskalov** [omarkhatibco/tailwind-css-variables#12]
Using a tuple of the form `[fontSize, { letterSpacing, lineHeight }]`  result in `[object Object]` in CSS variables.

![image](https://user-images.githubusercontent.com/63586825/98160618-185da100-1ee7-11eb-8024-1b1854682ab4.png)
![image](https://user-images.githubusercontent.com/63586825/98160387-ce74bb00-1ee6-11eb-9dcb-f5142f7968e2.png)
![image](https://user-images.githubusercontent.com/63586825/98160509-f8c67880-1ee6-11eb-9270-9b4944db9bdb.png)

**Comment by omarkhatibgg** [comment]
Hi @kiril-daskalov,

Thanks for reporting, I will check it ASAP.

**Comment by omarkhatibgg** [comment]
Hi @kiril-daskalov,

should works now, I rewrote it from scratch.
