### ISSUE TITLE
Update for v1.0

### ISSUE THREAD

**Issue by JayBizzle** [omarkhatibco/tailwind-css-variables#2]
Any chance there will be an update for Tailwind v1.0

I managed to hack something together to get it working temporarily in a project i needed it for, but official support would be great 👍

**Comment by omarkhatibgg** [comment]
Hi @JayBizzle  
Sure, once Tailwind hit v1 I will update it directly.

**Comment by JayBizzle** [comment]
Brilliant, thanks!

**Comment by Knovour** [comment]
Here comes 1.0 
https://tailwindcss.com/docs/upgrading-to-v1/

**Comment by omarkhatibgg** [comment]
You will get it soon.

**Comment by omarkhatibgg** [comment]
Hi @Knovour , @JayBizzle 
The new version in live in `next` tag. 

```bash
npm i tailwind-css-variables@next
```
Please check it give me a feedback.

also a working Example is here.

https://github.com/omarkhatibco/playground

**Comment by omarkhatibgg** [comment]
it's live now.
