### ISSUE TITLE
Still working?

### ISSUE THREAD

**Issue by ispyinternet** [omarkhatibco/tailwind-css-variables#7]
I can't for the life of me get this to work with my postcss setup.

I don't know if the issue is postcss-each is outdated and not playing with the latests postcss?

Do you know if this should still work with latest postcss and if so could you give an example postcss.config.js ?

I was using sass syntax, but I've stripped all that out and facing the same issue.

I had wondered if your plugin could have an option to output sass variables so that we could process using sass @each?

Cheers.

**Comment by omarkhatibgg** [comment]
Hi @ispyinternet  

can you share your postcss config with me please ?

I can not export sass variables since SASS is a `preprocesser` and Postcss is a `postprocesser` 

so sass is working just before postcss.

but to be honest: I was to perform all SASS functions with just Postcss with some limitations.

**Comment by ispyinternet** [comment]
something along these lines:

```
module.exports = {
    use: [
        ['sass', {
            includePaths: [
                './src/theme'
            ]
        }]
    ],
    syntax: 'postcss-scss',
    plugins: [
       require('tailwindcss')(path.resolve(__dirname, 'tailwind.config.js')),
       require('postcss-at-rules-variables'),
       require('postcss-each'),
       require('autoprefixer')(),
       require("cssnano")({
            preset: "default"
        })
    ]
};
```
with:
```
@each $key in var(--colors) {
    .btn-$key {
        color: var(--color-$(key));
    }
}

```
I can see your plugin working fine. all the css variables are output.
the compile error when trying to use in conjuction with postcss-each:
```
Invalid CSS after "...r: var(--color-": expected expression (e.g. 1px, bold), was "$(key));"
```
I think its perhaps sass intercepting the @each before postcss-each, I have tried stripping back and _think_ I removed sass pre-processer but I've got so much going on and its painful!

Not really your problem, just wondered if you knew if it was still a working solution, postcss-each doesn't appear to have been updated in a long while.

**Comment by omarkhatibgg** [comment]
HI @ispyinternet 

what about name the file `.css` instead of `.scss` and then I think sass compiler will (I hope) ignore it.

**Comment by ispyinternet** [comment]
Yh, I'll try a few more approaches. Thanks!
