### ISSUE TITLE
Tailwind utility classes still point to actual color instead of the custom property

### ISSUE THREAD

**Issue by AndrewBogdanovTSS** [omarkhatibco/tailwind-css-variables#8]
I decided to try your plugin. Although :root variables are generated fine
https://take.ms/ziYp8

Tailwind utility classes still point to an actual color instead of the custom property 
https://take.ms/2oSlR

Is it expected behavior? I would like my utility classes to point to the custom properties

**Comment by omarkhatibgg** [comment]
Hi @AndrewBogdanovTSS 
This plugin does not change Tailwind classes to css variables.
it just generate the css variables from you config and store it in :root.

The purpose  why I made this plugin: I was in a situation  where i could not able to use tailwind classes nor `@apply` directive  so css variables were much better for me.

> I would like my utility classes to point to the custom properties.

Check Adam Wathan  answer on  how you can achieve this.  [https://github.com/tailwindcss/tailwindcss/issues/260#issuecomment-348182548](#260)


I will close this issue for now, feel free to reopen it & I'm happy to help you.

**Comment by liaoliaojun** [comment]
Hi @AndrewBogdanovTSS 
This is the example you want： https://github.com/liaoliaojun/cssvars-playground
